apiVersion: v1
kind: Service
metadata:
  name: natours
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8099
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: natours
    app.kubernetes.io/instance: natours
